In [1]:
import pandas as pd

df = pd.read_csv('data/raw_data.csv')

In [ ]:
# 학과명 채우기
df.loc[0:3, '학과명'] = '컴퓨터공학전공'
df.loc[4:15, '학과명'] = '소프트웨어전공'
df.loc[16:21, '학과명'] = '정보통신공학전공'
df.loc[23:31, '학과명'] = '인공지능전공'
df.loc[32:48, '학과명'] = '소프트웨어융합전공'
df.loc[49:51, '학과명'] = '빅데이터응용전공'
df.loc[51:, '학과명'] = '인공지능전공'

In [22]:
#학부명 채우기
df.loc[0:31, '학부명'] = 'IT융합자율학부'
df.loc[32:48, '학부명'] = '소프트웨어융합학부'
df.loc[49:, '학부명'] = '미래융합학부'

In [24]:
#이수구분 none값 지우기
df = df[df['이수구분'].notna()]

In [26]:
#강의평가 이후 컬럼 삭제
df = df.loc[:, :'강의평가']

In [28]:
#인덱스 초기화
df = df.reset_index(drop=True)

In [29]:
df

,학부명,학과명,강의명,교수명,이수구분,선수과목과수강요건,학습내용,수업진행방식,별점,강의평가
0,IT융합자율학부,컴퓨터공학전공,게임프로그래밍,임충규,전공선택,C++프로그래밍'또는'컴퓨터그래픽스',1. Unity 게임 엔진 및 편집기 사용법\r\n2. 게임 레벨 디자인\r\n3....,각 주제에 대하여 강의와 시연을 통하여 게임 개발에 필요한 주요 기술을 이해하며 주...,NaN,없음
1,IT융합자율학부,컴퓨터공학전공,디지털영상처리,김학수,전공선택,"파이썬프로그래밍, 신호및시스템",1. 디지털 영상처리의 응용 분야 및 이를 구현하기 위한 방법들을 소개한다.\r\n...,1. 매 장마다 이론과 실습을 병행한다.\r\n2. 매 장이 끝나면 실습과제를 수행...,NaN,없음
2,IT융합자율학부,컴퓨터공학전공,컴퓨터공학캡스톤디자인,임충규,전공필수,"프로젝트 수행에 필요한 기초, 핵심 과목",1. 컴퓨터 어플리케이션의 개발 과정 이해\n2. 개발 대상 어플리케이션의 요구사항...,- 3인의 팀을 구성하고 학기초에 프로젝트 제안서를 제줄하여 승인 후 프로젝트를 수...,NaN,없음
3,IT융합자율학부,컴퓨터공학전공,AR/VR시스템개발,임충규,전공선택,컴퓨터그래픽스 또는 게임프로그래밍,1. 유니티 게임엔진 소개\r\n2. Vuforia 사용법\r\n3. Oculus ...,- 강의 60%\r\n- 실습 40%,NaN,없음
4,IT융합자율학부,소프트웨어전공,운영체제,노은하,전공필수,"Java프로그래밍, 자료구조, 컴퓨터구조의 기본 개념을 갖추고 있으면 수강에 도움이...","컴퓨터 시스템의 개요, 운영체제 개념, 발전과정, 운영체제 구조, 프로세스와 스레드...","- 강의 70%\r\n- 퀴즈와 과제 수행 30%\r\n- 강의를 주로 하되, 각 ...",4.40,과제는 ppt로 발표자료 만드는거랑 (발표는 희망자만) 다른 분반 퀴즈 풀기고 한 ...
5,IT융합자율학부,소프트웨어전공,알고리즘,노은하,전공필수,* 선수필수 과목 : 자료구조 * 실습/과제 수행을 위해 Java프로그래밍 선수...,"- 정렬, 선택 알고리즘, 검색트리, 해시 테이블, 상호 배타적 집합의 처리, 동적...","- 강의 50%, 실습 50% \r\n- 학습 내용을 실습을 통해 확인하며, 결과...",4.25,"잘 가르쳐주시는 교수님, 코드를 시각적으로 하나하나 보여주시는 것에서 학생들을 참 ..."
6,IT융합자율학부,소프트웨어전공,프론트엔드 개발,이승진,전공선택,"웹개발입문(필수), Java프로그래밍 (필수). (참고: 프론트엔드개발을 ...",javascript language\r\nVue.js\r\naxios 서버 통신,강의 80% 실습 20%,NaN,NaN
7,IT융합자율학부,소프트웨어전공,시스템분석 및 설계,문성현,전공선택,없음,강의에서는 먼저 시스템 개발 생명 주기 및 시스템 개발 방법론 등 이론을 설명한 다...,설계 표준 언어인 UML(Unified Modeling Language)과 객체지향...,4.00,개인적으로 조별과제가 많아 조원 운이 없으면 듣기 힘든 과목이라고 생각한다. 조원은...
8,IT융합자율학부,소프트웨어전공,빅데이터실무,신하진,전공선택,NaN,NaN,본 강의는 이론 학습과 실습(hands-on)을 단계적으로 결합하여 진행된다.\r\...,NaN,x
9,IT융합자율학부,소프트웨어전공,네트워크 프로그래밍,이승진,전공선택,"Java프로그래밍 (필수), 자료구조 (권장)",Java 네트워크 프로그래밍 기술을 학습한다.\r\n- 멀티 스레드 작업 구현\r\...,1. 필요한 이론을 교수가 설명한다.\r\n2. 예제 소스 코드를 교수가 설명한다....,5.00,이승진 교수님 강의 중 가장 자바 기본기가 중요하다고 느껴졌음. 스트림 공부 잘하고...
10,IT융합자율학부,소프트웨어전공,인공지능,김명철,전공선택,자료구조론은 선수 필수과목이며 기타 여러 컴퓨터 과목과 연계하여 수강할 수 있다.,NaN,"주교재를 이용한 강의와 실습을 하고, 각자의 학기과제 주제에 따른 조사발표 및 보고...",4.00,"비대면으로 조별활동이 까다롭고, 과제에 대한 설명이 많이 아쉬움. 그래도 전선으로 ..."
11,IT융합자율학부,소프트웨어전공,백엔드프레임워크,이승진,전공선택,"웹프로그래밍 (필수), 데이터베이스 (필수)",고급 Java 웹 서버 애플리케이션 개발에 필요한 다음과 같은 기술들을 학습한다.\...,강의 50%\r\n실습 50% \r\n\r\n매주 학습한 내용을 실습해 볼 수 있...,4.67,"웹프로그래밍을 듣고, 백엔드프레임워크를 바로 다음 학기에 들었는데 난이도가 꽤 올라..."
12,IT융합자율학부,소프트웨어전공,Java 프로젝트,문성현,전공선택,Java프로그래밍,"Java 기반 그래픽, 이벤트 처리, 멀티태스킹 등의 프로그래밍 기법을 학습하고 팀...","1) 이론 강의, 예제 코드 리뷰, 프로그래밍 실습, 프로젝트 발표를 병행한다.\r...",1.00,자바를 잘 아는 사람만 수강하길 바람 난 별로였음 - 25년 1학기 수강자 (1/5)
13,IT융합자율학부,소프트웨어전공,통계자료분석 및 실습,윤명호,전공선택,없음,주요 내용은 통계 기초 개념 및 통계분석방법론 등을 학습한다.\r\n이를 위해 간단...,이론 강의와 실습\r\n\r\n[공휴일 예정사항]\r\n추석 - 동영상 수업(10/...,1.70,"진짜 최악이다. ㅋㅋ 강의력도 너무 안 좋고, 자세히 가르쳐 주지도 않음. 강의자료..."
14,IT융합자율학부,소프트웨어전공,졸업지도,김명철,전공필수,없음.,- 졸업 준비로서 수행할 목표를 스스로 설정하고 달성한다.\r\n- 졸업 후 취업 ...,"- 4학년 학생을 대상으로 하여, 스스로에게 부여한 과제를 수행하고 경력을 관리하고...",NaN,x
15,IT융합자율학부,소프트웨어전공,프론트엔드프레임워크,이승진,전공선택,프론트엔드개발 (필수),"* Typescript 문법\r\n* React.js, Next.js 프레임워크\r...",강의 50% 실습 50%,5.00,이번학기 새로 계설된 수업이어서 앞으로 수업 내용의 변화의 여지가 좀 있을 것 같습...
16,IT융합자율학부,정보통신공학전공,사물인터넷,정인철,전공선택,- 리눅스시스템- 파이썬- C 언어에 대한 이해가 있으면 되움이 됨.,본 수업에서는 IoT 소프트웨어를 프로그래밍할 수 있는 오픈 소스 컴퓨터인 라즈베리...,"본 수업은 이론 설명과 실습을 통하여 진행한다. 즉, 이론을 설명하고, 각 학생들은...",3.00,"그냥 괜찮긴 한데 중간, 기말 시험 점수 알려주지 않고 시험문제는 알려주지도 않은거..."
17,IT융합자율학부,정보통신공학전공,네트워크 프로그래밍,박정식,전공선택,"본 수업은 선수 과목이 없도록 설계 되었으나, 네트워크 프로그래밍을 배우는 교과목이...",1. 강좌 개요 설명 및 네트워크 프로그래밍이 필요한 이유와 적용 분야에 대하여 ...,"- 본 강좌는 주로 강의와 실습을 통하여 수업을 진행하며, 필요시 유인물과 파워포인...",NaN,x
18,IT융합자율학부,정보통신공학전공,임베디드시스템,이종현,전공선택,"- 본 과목은 선수 과목은 없으나, 컴퓨터 구조론, C언어, 디지털논리회로실습, 사...","임베디드 시스템에 활용하는 각종 센서류와 그 응용에 대해 공부하고, 이를 하드웨어로...",강의 50% 실습 50% \r\n본강의는 실습 대면으로 이루어지며 중간고사는 필답고...,5.00,"가장 좋아하는 종현교수님의 강의, 비록 많은 프로젝트 준비량에 허덕였지만 그만큼 배..."
19,IT융합자율학부,정보통신공학전공,인터넷보안,이종현,전공선택,"- 본 과목은 선수 과목은 없으나, 생활속의 보안, 보안 시스템, 데이터 통신, 컴...","인터넷 보안 교과목에서는 다음과 같은 내용을 학습한다.\r\n- CCNA, CCIE...",- 강의 40% 실습 40% 질의 응답 20% \r\n- 중간고사나 기말고사는 공정...,4.00,보안에 관해서 알 수 있어서 너무너무 좋았어요! 정보통신학과라면 꼭 들었으면 하는 ...
20,IT융합자율학부,정보통신공학전공,TCP/IP,박정식,전공선택,이 과목은 따로 선수 과목이 필요하지 않다. 그러나 2학년 2학기에 개설한 데이터통...,1. IPv4 프로토콜의 주소지정 메카니즘인 IPv4 주소 지정에 대하여 학습한다...,강의는 대부분 교수가 직접 강의를 하며 강의 후 연습문제를 과제로 제시한다.\n교수...,NaN,x
21,IT융합자율학부,정보통신공학전공,정보보호개론,이종현,전공선택,"정보보안의 특성상, 모든 IT관련 지식이 있어야 쉽게 수강할 수 있습니다. 특히 생...","본과목에서는 정보보호개념, 암호학, 정보보호관리, 정보보호법 등을 배우고, 특히 기...","수업은 대면으로 강의실에서 이루어지며, 필요에 따라 간단한 실습이 적용될 수 있음\...",5.00,교수님 열정있고 재미있는 수업입니다. 교수님 열정맨 - (5/5)\n\n개론이다보...
22,IT융합자율학부,인공지능전공,심층신경망,곽승우,전공선택,머신러닝,"- 인공 신경망 모델의 훈련 및 최적화 기법\r\n- 합성곱 신경망, 순환 신경망,...","1) 이론 강의, 예제 코드 리뷰, 프로그래밍 실습을 병행한다.\r\n2) 매 주 ...",NaN,x
23,IT융합자율학부,인공지능전공,인공지능문제해결,이상윤,전공선택,없음,- 데이터 분석 및 시각화\r\n- 실전 프로젝트 수행\r\n- 프로젝트 관리와 협...,"문제에 대한 설명과 접근 방법을 소개하고, 스스로 문제를 해결하기 위한 실습을 진행...",NaN,x
24,IT융합자율학부,인공지능전공,인공지능수학,곽승우,전공선택,"- <선형대수학>을 포함한 수업을 수강하였다면 도움이 될 것이지만, 수강하지 않았다...",1. 수학적인 이론의 이해를 통해 인공지능이 작동하는 원리를 이해한다.\r\n2. ...,"1. 이론에 대한 수업 후, Python을 실습\r\n2. 필기구를 가져올 것을 추...",4.00,시험도 그렇게 안어렵고 무난해요. 수학 잘하면 학점 채우기로 들으시고 못하면 배우려...
25,IT융합자율학부,인공지능전공,강화학습,이상윤,전공선택,없음,1. 강화학습의 기초 이론부터 딥러닝이 결합된 심층 이론까지 전반적이고 핵심적인 이...,대면 (이론 및 실습),NaN,x
26,IT융합자율학부,인공지능전공,디지털영상처리,곽승우,전공선택,없음,1. 규칙 기반의 고전적인 방법론부터 기계학습의 방법론까지의 원리와 기술을 폭넓게 ...,1. 초반은 Python에 대한 수업과 이미지 및 비디오 데이터를 처리하는 이론 ...,NaN,x
27,IT융합자율학부,인공지능전공,인턴십1,이상윤,전공선택,인턴십이 확정되어 담당교수의 승인을 득한 학생에 한하여 본 과목을 수강할 수 있습니다.,국내외 기업 또는 기관의 인턴십이 확정된 학생들은 담당교수의 사전 승인하에 본 교과...,"국내기업에서 위탁교육\r\n해당분야 팀장이 근무태도, 근무실적, 출석률을 고려하여 ...",NaN,NaN
28,소프트웨어융합학부,소프트웨어융합전공,Java프로그래밍,김선형,전공탐색,* 웹개발입문을 수강신청하기 위한 선수필수 과목: 없음* 웹개발입문을 이수해야 수강...,"1. HTML5 개요, 기본 태그를 이용한 문서 만들기\n2. HTML5 문서 구조...",강의를 통해 웹 표준 기술의 주요 개념과 동작 원리를 설명한다.\n실습을 통해 웹 ...,4.67,무난무난한 자바 수업 과제는 총 10번 시험기간빼고 거의 매주 주신다 생각하면 될듯...
29,소프트웨어융합학부,소프트웨어융합전공,데이터베이스,홍은지,전공선택,"""데이터베이스""는 ""백엔드프레임워크"" 과목을 위한 선수필수과목이고, ""웹프로그래밍""...","강의를 통해 데이터베이스의 개념을 이해한 후, 실제 데이터베이스 관리 시스템을 사용...","강의 50% 실습 50% 매주 퀴즈를 진행하여, 학습한 내용을 복습하고 평가한다. ...",4.21,발표가 의미 있나 싶은.. 교수님은 참 좋으심 강의도 열심히 해주시고 학생들 아끼는...
30,소프트웨어융합학부,소프트웨어융합전공,데이터통신,박정식,전공선택,"본 수업은 선수 과목이 없도록 설계 되었으며, 데이터통신의 개념을 잡기 위해 설계된...","1. 데이터통신 개요를 설명하며, 강좌 개요와 데이터 통신의 개요에 대하여 배운다....",- 파워포인트를 이용한 이론 강의\r\n- 강의 80% 질의응답 20%,NaN,x
31,소프트웨어융합학부,소프트웨어융합전공,논리회로설계,정인철,전공선택,없음,"1. 수의 체계와 정보의 부호화, 부울대수의 개념을 이해한다.\r\n2. 인코더/디...",주로 강의를 통해 디지털 논리회로의 개념을 이해시킨다.\r\n매 단원이 끝날 때 연...,4.67,시험 망했는데 B+ 받음 수업은 어렵지만 자기가 그래도 자진해서 독학하면 잘 볼 수...
32,소프트웨어융합학부,소프트웨어융합전공,전공지도,이하규,전공필수,없음,- 현재 학기의 수강신청 상황을 점검하고 다음 학기 수강신청에 대해 지도한다.\r\...,"개인 발표/토론과 조별 발표/토론을 중심으로 수업이 이루어지며,\r\n개인별 심층 ...",NaN,x
33,소프트웨어융합학부,소프트웨어융합전공,C++프로그래밍,이하규,전공선택,C프로그래밍,1. C++ 언어의 문법을 익힌다.\r\n2. 객체지향 프로그래밍의 개념을 숙지한다...,"매주 학습한 내용을 활용하는 과제가 주어지며, 이를 해결하여 제출해야 합니다.\r\...",4.80,항상 높은 퀄리티로 강의해주시는 교수님 C++ 듣고 싶은 학우분은 이하규 교수님 꼭...
34,소프트웨어융합학부,소프트웨어융합전공,자료구조,김명철,전공필수,- 자바 프로그래밍,1. 컴퓨터 프로그래밍에 사용되는 기본 자료구조를 소개한다. \r\n2. 알고리즘의...,- 강의 50%\r\n- 실습 50% \r\n- 매주 학습한 내용을 활용하는 과제...,3.33,매주 과제있고 매 수업마다 조별로 실습 ? 통과해야함 그래서 그 실습 통과하려고 공...
35,소프트웨어융합학부,소프트웨어융합전공,자료구조,노은하,전공필수,선수필수 과목 : Java프로그래밍,1. 컴퓨터 프로그래밍에 사용되는 기본 자료구조를 소개한다. \r\n2. 알고리즘의...,- 강의 50%\r\n- 실습 50% \r\n- 학습한 내용을 활용하는 프로그래밍...,5.00,"교수님이 상당히 잘 알려주시고, 궁금한것도 잘 받아주심. -( 5/5)\n\n소프..."
36,소프트웨어융합학부,소프트웨어융합전공,컴퓨터구조,김학수,전공선택,논리회로설계,"컴퓨터 시스템 개요, CPU의 구조와 기능, 산술과 논리 연산, 제어 장치, 기억 ...",1. 강의를 통해 컴퓨터 시스템의 구조와 원리를 설명한다. \r\n2. 단원마다 간...,4.25,연습문제 다 이해하고 푸시면 A+입니다 교수님 부드러우시고 좋아요 - (5/5)\n...
37,소프트웨어융합학부,소프트웨어융합전공,컴퓨터구조,정인철,전공선택,논리회로설계를 이수한 경우에는 도움이 됨,"컴퓨터 시스템 개요, CPU의 구조와 기능, 산술과 논리 연산, 제어 장치, 기억 ...",강의는 대부분 교수가 직접 강의를 하며 수시로 퀴즈와 토론을 포함하는 강의를 진행한...,4.00,시험 연습문제 난이도로 내시고 학점도 잘 주심 정인철 교수님 폼 미쳤다! - (5...
38,소프트웨어융합학부,소프트웨어융합전공,JSP프로그래밍,박정식,전공선택,본 과목을 이수해야 백엔드프레임워크 과목을 수강 신청할 수 있습니다.,웹프로그래밍 구조에 대하여 배우고 이클립스 통합개발환경을 통하여 직접 JSP프로그램...,파워포인트를 활용한 이론강의와 컴퓨터를 활용한 실습을 병행한다.,NaN,x
39,소프트웨어융합학부,소프트웨어융합전공,백엔드프로그래밍,김선형,전공선택,"* 백엔드프로그래밍을 수강신청하기 위한 선수필수 과목: 웹개발입문, Java프로그래...","웹 개발 기초: HTML, CSS, JS\n데이터베이스 기초: SQL, MySQL\...",강의를 통해 웹 프로그래밍의 동작 원리를 설명한다.\r\n실습을 통해 웹 서버 애플...,NaN,x
40,소프트웨어융합학부,소프트웨어융합전공,컴퓨터네트워크,박정식,전공선택,이 과목은 2학년 2학기에 개설한 데이터통신과목을 연장하여 강의를 진행하므로 데이터...,- 컴퓨터 네트워크 프로토콜 모델에 대해 이해한다.\n- TCP/IP 프로토콜 스택...,교수강의 80%\r\n연습문제풀이 10%\r\n점검 및 조언 10%\r\n강의는 대...,5.00,영어 원서+영어 PPT라서 시험 기간에 벼락치기할 때 조금 힘들었음.. 근데 수업은...
41,소프트웨어융합학부,소프트웨어융합전공,디지털회로실험,정인철,전공선택,논리회로설계를 이수한 경우 도움이 됨,1. 각종 계측장비의 사용법에 대해 익히고 다룰수 있도록 한다.\r\n2. 기초 전...,본 강과는 주로 실험 실습을 통해 이루어진다.\r\n학생들의 이해를 향상시키기 위해...,5.00,정통에서 믿고 듣는 정인철 교수님 시험은 역시 어려운 편임. 문제 수가 많지는 않았...
42,소프트웨어융합학부,소프트웨어융합전공,서버구축및형상관리,이승진,전공선택,"꼭 필요한 선수 과목은 없지만, 웹프로그래밍 과목을 먼저 수강해야 서버 구축 실습 ...",git을 활용한 형상 관리 기법을 학습한다.\r\n정보시스템 서버를 구축하기 위해 ...,강의 50%\r\n실습 50% \r\n\r\n매주 학습한 내용을 실습해 볼 수 있...,4.60,"깃과 깃허브, 리눅스 명령어랑 AWS 간단하게 배움 깃과 깃허브 아예 처음이라면 이..."
43,소프트웨어융합학부,소프트웨어융합전공,신호및시스템,김학수,전공선택,"공업수학, 파이썬프로그래밍",1. 신호 및 시스템의 개념 및 응용 사례\r\n2. 연속시간 주기 신호와 비주기 ...,1. 신호 및 시스템의 개념과 이론을 설명한다. \r\n2. 파이썬 프로그래밍을 통...,NaN,x
44,소프트웨어융합학부,소프트웨어융합전공,웹디자인,이해신,전공선택,소프트웨어융합전공에서 웹개발입문 교과목을 이수해야 수강 신청 가능한 과목은 Java...,"- HTML, CSS 등 웹 디자인 기술을 활용한 웹 페이지 제작 기술\n- CSS...","이론 설명 후 컴퓨터를 활용한 실습 위주의 수업\r\n이론 강의 30%, 실습 70%",NaN,x
45,미래융합학부,빅데이터응용전공,경영정보시스템의이해,김수림,전공필수,없음,"경영정보시스템의 개념과 구조에 대한 이해를 바탕으로, 기업 내 다양한 시스템이 어떤...",1. 이론 설명\n2. 강의시간 내 그룹활동\n3. 개인발표\n4. 중간/기말고사,NaN,x
46,미래융합학부,빅데이터응용전공,빅데이터처리와시각화,김양희,전공선택,없음,"데이터 문해력의 개념과 중요성에 대한 이론적 탐구를 바탕으로, 다양한 실제 사례 분...",1. 개인 레포트\n2. 중간/기말고사\n,NaN,x
47,미래융합학부,인공지능전공,빅데이터프로그래밍(Python),김수림,전공필수,없음,데이터 기반 의사결정을 위한 빅데이터 프로그래밍의 개념과 필요성에 대한 이해를 시작...,1. 이론 소개 및 실습 진행\n2. 강의 내용을 바탕으로 기말고사 전 개인 과제에...,NaN,x
48,미래융합학부,인공지능전공,머신러닝입문,홍성준,전공필수,Python프로그래밍,머신 러닝의 주요 개념과 모델을 학습하고 머신 러닝 라이브러리인 사이킷런과 텐서플로...,"1) 이론 강의, 예제 코드 리뷰, 프로그래밍 실습을 병행한다.\r\n2) 매 주 ...",5.00,"강의가 깔끔해서? 좋았음 시험은 실습보다 개념, 이론 위주로 나옴 과제는 진도 나갈..."
49,미래융합학부,인공지능전공,데이터사이언스입문,이상윤,전공필수,Python프로그래밍을 수강했거나 Python 기초 역량이 있는 학생을 대상으로 합...,"1) 데이터 전처리, 시각화, 결과 분석 등 일련의 데이터 분석 과정을 학습한다.\...",본 교과목은 플립러닝(Flipped Learning) 방식으로 진행됩니다.\r\n-...,5.00,python에서 사용할 수 있는 데이터 처리 라이브러리인 pandas를 기반으로 데...
50,미래융합학부,인공지능전공,고급Python프로그래밍,홍성준,전공선택,Python프로그래밍,다양한 파이썬 라이브러리를 이해하고 이를 활용한 파이썬 프로그램 구현을 실 습한다.,"1) 이론 강의, 예제 코드 리뷰, 프로그래밍 실습을 병행한다.\r\n2) 매 주 ...",NaN,x
51,미래융합학부,인공지능전공,오픈소스SW개발,이상윤,전공선택,없음,- 오픈소스 소프트웨어 이해\r\n- 개발 환경 구축 및 관리\r\n- 분산 버전관...,"실습 위주의 수업으로 진행되며, 중간고사와 기말고사는 각각 개인프로젝트와 팀프로젝트...",NaN,x

In [31]:
#선수과목과수강요건 none값 '없음'으로 채우기
df['선수과목과수강요건'] = df['선수과목과수강요건'].fillna('없음')

In [34]:
#별점 none값 '없음'으로 채우기
df['별점'] = df['별점'].fillna('없음')

In [38]:
df['강의평가'] = df['강의평가'].fillna('없음')

In [ ]:
df['학습내용'] = df['학습내용'].fillna('없음')

In [41]:
df

,학부명,학과명,강의명,교수명,이수구분,선수과목과수강요건,학습내용,수업진행방식,별점,강의평가
0,IT융합자율학부,컴퓨터공학전공,게임프로그래밍,임충규,전공선택,C++프로그래밍'또는'컴퓨터그래픽스',1. Unity 게임 엔진 및 편집기 사용법\r\n2. 게임 레벨 디자인\r\n3....,각 주제에 대하여 강의와 시연을 통하여 게임 개발에 필요한 주요 기술을 이해하며 주...,없음,없음
1,IT융합자율학부,컴퓨터공학전공,디지털영상처리,김학수,전공선택,"파이썬프로그래밍, 신호및시스템",1. 디지털 영상처리의 응용 분야 및 이를 구현하기 위한 방법들을 소개한다.\r\n...,1. 매 장마다 이론과 실습을 병행한다.\r\n2. 매 장이 끝나면 실습과제를 수행...,없음,없음
2,IT융합자율학부,컴퓨터공학전공,컴퓨터공학캡스톤디자인,임충규,전공필수,"프로젝트 수행에 필요한 기초, 핵심 과목",1. 컴퓨터 어플리케이션의 개발 과정 이해\n2. 개발 대상 어플리케이션의 요구사항...,- 3인의 팀을 구성하고 학기초에 프로젝트 제안서를 제줄하여 승인 후 프로젝트를 수...,없음,없음
3,IT융합자율학부,컴퓨터공학전공,AR/VR시스템개발,임충규,전공선택,컴퓨터그래픽스 또는 게임프로그래밍,1. 유니티 게임엔진 소개\r\n2. Vuforia 사용법\r\n3. Oculus ...,- 강의 60%\r\n- 실습 40%,없음,없음
4,IT융합자율학부,소프트웨어전공,운영체제,노은하,전공필수,"Java프로그래밍, 자료구조, 컴퓨터구조의 기본 개념을 갖추고 있으면 수강에 도움이...","컴퓨터 시스템의 개요, 운영체제 개념, 발전과정, 운영체제 구조, 프로세스와 스레드...","- 강의 70%\r\n- 퀴즈와 과제 수행 30%\r\n- 강의를 주로 하되, 각 ...",4.4,과제는 ppt로 발표자료 만드는거랑 (발표는 희망자만) 다른 분반 퀴즈 풀기고 한 ...
5,IT융합자율학부,소프트웨어전공,알고리즘,노은하,전공필수,* 선수필수 과목 : 자료구조 * 실습/과제 수행을 위해 Java프로그래밍 선수...,"- 정렬, 선택 알고리즘, 검색트리, 해시 테이블, 상호 배타적 집합의 처리, 동적...","- 강의 50%, 실습 50% \r\n- 학습 내용을 실습을 통해 확인하며, 결과...",4.25,"잘 가르쳐주시는 교수님, 코드를 시각적으로 하나하나 보여주시는 것에서 학생들을 참 ..."
6,IT융합자율학부,소프트웨어전공,프론트엔드 개발,이승진,전공선택,"웹개발입문(필수), Java프로그래밍 (필수). (참고: 프론트엔드개발을 ...",javascript language\r\nVue.js\r\naxios 서버 통신,강의 80% 실습 20%,없음,없음
7,IT융합자율학부,소프트웨어전공,시스템분석 및 설계,문성현,전공선택,없음,강의에서는 먼저 시스템 개발 생명 주기 및 시스템 개발 방법론 등 이론을 설명한 다...,설계 표준 언어인 UML(Unified Modeling Language)과 객체지향...,4.0,개인적으로 조별과제가 많아 조원 운이 없으면 듣기 힘든 과목이라고 생각한다. 조원은...
8,IT융합자율학부,소프트웨어전공,빅데이터실무,신하진,전공선택,없음,없음,본 강의는 이론 학습과 실습(hands-on)을 단계적으로 결합하여 진행된다.\r\...,없음,x
9,IT융합자율학부,소프트웨어전공,네트워크 프로그래밍,이승진,전공선택,"Java프로그래밍 (필수), 자료구조 (권장)",Java 네트워크 프로그래밍 기술을 학습한다.\r\n- 멀티 스레드 작업 구현\r\...,1. 필요한 이론을 교수가 설명한다.\r\n2. 예제 소스 코드를 교수가 설명한다....,5.0,이승진 교수님 강의 중 가장 자바 기본기가 중요하다고 느껴졌음. 스트림 공부 잘하고...
10,IT융합자율학부,소프트웨어전공,인공지능,김명철,전공선택,자료구조론은 선수 필수과목이며 기타 여러 컴퓨터 과목과 연계하여 수강할 수 있다.,없음,"주교재를 이용한 강의와 실습을 하고, 각자의 학기과제 주제에 따른 조사발표 및 보고...",4.0,"비대면으로 조별활동이 까다롭고, 과제에 대한 설명이 많이 아쉬움. 그래도 전선으로 ..."
11,IT융합자율학부,소프트웨어전공,백엔드프레임워크,이승진,전공선택,"웹프로그래밍 (필수), 데이터베이스 (필수)",고급 Java 웹 서버 애플리케이션 개발에 필요한 다음과 같은 기술들을 학습한다.\...,강의 50%\r\n실습 50% \r\n\r\n매주 학습한 내용을 실습해 볼 수 있...,4.67,"웹프로그래밍을 듣고, 백엔드프레임워크를 바로 다음 학기에 들었는데 난이도가 꽤 올라..."
12,IT융합자율학부,소프트웨어전공,Java 프로젝트,문성현,전공선택,Java프로그래밍,"Java 기반 그래픽, 이벤트 처리, 멀티태스킹 등의 프로그래밍 기법을 학습하고 팀...","1) 이론 강의, 예제 코드 리뷰, 프로그래밍 실습, 프로젝트 발표를 병행한다.\r...",1.0,자바를 잘 아는 사람만 수강하길 바람 난 별로였음 - 25년 1학기 수강자 (1/5)
13,IT융합자율학부,소프트웨어전공,통계자료분석 및 실습,윤명호,전공선택,없음,주요 내용은 통계 기초 개념 및 통계분석방법론 등을 학습한다.\r\n이를 위해 간단...,이론 강의와 실습\r\n\r\n[공휴일 예정사항]\r\n추석 - 동영상 수업(10/...,1.7,"진짜 최악이다. ㅋㅋ 강의력도 너무 안 좋고, 자세히 가르쳐 주지도 않음. 강의자료..."
14,IT융합자율학부,소프트웨어전공,졸업지도,김명철,전공필수,없음.,- 졸업 준비로서 수행할 목표를 스스로 설정하고 달성한다.\r\n- 졸업 후 취업 ...,"- 4학년 학생을 대상으로 하여, 스스로에게 부여한 과제를 수행하고 경력을 관리하고...",없음,x
15,IT융합자율학부,소프트웨어전공,프론트엔드프레임워크,이승진,전공선택,프론트엔드개발 (필수),"* Typescript 문법\r\n* React.js, Next.js 프레임워크\r...",강의 50% 실습 50%,5.0,이번학기 새로 계설된 수업이어서 앞으로 수업 내용의 변화의 여지가 좀 있을 것 같습...
16,IT융합자율학부,정보통신공학전공,사물인터넷,정인철,전공선택,- 리눅스시스템- 파이썬- C 언어에 대한 이해가 있으면 되움이 됨.,본 수업에서는 IoT 소프트웨어를 프로그래밍할 수 있는 오픈 소스 컴퓨터인 라즈베리...,"본 수업은 이론 설명과 실습을 통하여 진행한다. 즉, 이론을 설명하고, 각 학생들은...",3.0,"그냥 괜찮긴 한데 중간, 기말 시험 점수 알려주지 않고 시험문제는 알려주지도 않은거..."
17,IT융합자율학부,정보통신공학전공,네트워크 프로그래밍,박정식,전공선택,"본 수업은 선수 과목이 없도록 설계 되었으나, 네트워크 프로그래밍을 배우는 교과목이...",1. 강좌 개요 설명 및 네트워크 프로그래밍이 필요한 이유와 적용 분야에 대하여 ...,"- 본 강좌는 주로 강의와 실습을 통하여 수업을 진행하며, 필요시 유인물과 파워포인...",없음,x
18,IT융합자율학부,정보통신공학전공,임베디드시스템,이종현,전공선택,"- 본 과목은 선수 과목은 없으나, 컴퓨터 구조론, C언어, 디지털논리회로실습, 사...","임베디드 시스템에 활용하는 각종 센서류와 그 응용에 대해 공부하고, 이를 하드웨어로...",강의 50% 실습 50% \r\n본강의는 실습 대면으로 이루어지며 중간고사는 필답고...,5.0,"가장 좋아하는 종현교수님의 강의, 비록 많은 프로젝트 준비량에 허덕였지만 그만큼 배..."
19,IT융합자율학부,정보통신공학전공,인터넷보안,이종현,전공선택,"- 본 과목은 선수 과목은 없으나, 생활속의 보안, 보안 시스템, 데이터 통신, 컴...","인터넷 보안 교과목에서는 다음과 같은 내용을 학습한다.\r\n- CCNA, CCIE...",- 강의 40% 실습 40% 질의 응답 20% \r\n- 중간고사나 기말고사는 공정...,4.0,보안에 관해서 알 수 있어서 너무너무 좋았어요! 정보통신학과라면 꼭 들었으면 하는 ...
20,IT융합자율학부,정보통신공학전공,TCP/IP,박정식,전공선택,이 과목은 따로 선수 과목이 필요하지 않다. 그러나 2학년 2학기에 개설한 데이터통...,1. IPv4 프로토콜의 주소지정 메카니즘인 IPv4 주소 지정에 대하여 학습한다...,강의는 대부분 교수가 직접 강의를 하며 강의 후 연습문제를 과제로 제시한다.\n교수...,없음,x
21,IT융합자율학부,정보통신공학전공,정보보호개론,이종현,전공선택,"정보보안의 특성상, 모든 IT관련 지식이 있어야 쉽게 수강할 수 있습니다. 특히 생...","본과목에서는 정보보호개념, 암호학, 정보보호관리, 정보보호법 등을 배우고, 특히 기...","수업은 대면으로 강의실에서 이루어지며, 필요에 따라 간단한 실습이 적용될 수 있음\...",5.0,교수님 열정있고 재미있는 수업입니다. 교수님 열정맨 - (5/5)\n\n개론이다보...
22,IT융합자율학부,인공지능전공,심층신경망,곽승우,전공선택,머신러닝,"- 인공 신경망 모델의 훈련 및 최적화 기법\r\n- 합성곱 신경망, 순환 신경망,...","1) 이론 강의, 예제 코드 리뷰, 프로그래밍 실습을 병행한다.\r\n2) 매 주 ...",없음,x
23,IT융합자율학부,인공지능전공,인공지능문제해결,이상윤,전공선택,없음,- 데이터 분석 및 시각화\r\n- 실전 프로젝트 수행\r\n- 프로젝트 관리와 협...,"문제에 대한 설명과 접근 방법을 소개하고, 스스로 문제를 해결하기 위한 실습을 진행...",없음,x
24,IT융합자율학부,인공지능전공,인공지능수학,곽승우,전공선택,"- <선형대수학>을 포함한 수업을 수강하였다면 도움이 될 것이지만, 수강하지 않았다...",1. 수학적인 이론의 이해를 통해 인공지능이 작동하는 원리를 이해한다.\r\n2. ...,"1. 이론에 대한 수업 후, Python을 실습\r\n2. 필기구를 가져올 것을 추...",4.0,시험도 그렇게 안어렵고 무난해요. 수학 잘하면 학점 채우기로 들으시고 못하면 배우려...
25,IT융합자율학부,인공지능전공,강화학습,이상윤,전공선택,없음,1. 강화학습의 기초 이론부터 딥러닝이 결합된 심층 이론까지 전반적이고 핵심적인 이...,대면 (이론 및 실습),없음,x
26,IT융합자율학부,인공지능전공,디지털영상처리,곽승우,전공선택,없음,1. 규칙 기반의 고전적인 방법론부터 기계학습의 방법론까지의 원리와 기술을 폭넓게 ...,1. 초반은 Python에 대한 수업과 이미지 및 비디오 데이터를 처리하는 이론 ...,없음,x
27,IT융합자율학부,인공지능전공,인턴십1,이상윤,전공선택,인턴십이 확정되어 담당교수의 승인을 득한 학생에 한하여 본 과목을 수강할 수 있습니다.,국내외 기업 또는 기관의 인턴십이 확정된 학생들은 담당교수의 사전 승인하에 본 교과...,"국내기업에서 위탁교육\r\n해당분야 팀장이 근무태도, 근무실적, 출석률을 고려하여 ...",없음,없음
28,소프트웨어융합학부,소프트웨어융합전공,Java프로그래밍,김선형,전공탐색,* 웹개발입문을 수강신청하기 위한 선수필수 과목: 없음* 웹개발입문을 이수해야 수강...,"1. HTML5 개요, 기본 태그를 이용한 문서 만들기\n2. HTML5 문서 구조...",강의를 통해 웹 표준 기술의 주요 개념과 동작 원리를 설명한다.\n실습을 통해 웹 ...,4.67,무난무난한 자바 수업 과제는 총 10번 시험기간빼고 거의 매주 주신다 생각하면 될듯...
29,소프트웨어융합학부,소프트웨어융합전공,데이터베이스,홍은지,전공선택,"""데이터베이스""는 ""백엔드프레임워크"" 과목을 위한 선수필수과목이고, ""웹프로그래밍""...","강의를 통해 데이터베이스의 개념을 이해한 후, 실제 데이터베이스 관리 시스템을 사용...","강의 50% 실습 50% 매주 퀴즈를 진행하여, 학습한 내용을 복습하고 평가한다. ...",4.21,발표가 의미 있나 싶은.. 교수님은 참 좋으심 강의도 열심히 해주시고 학생들 아끼는...
30,소프트웨어융합학부,소프트웨어융합전공,데이터통신,박정식,전공선택,"본 수업은 선수 과목이 없도록 설계 되었으며, 데이터통신의 개념을 잡기 위해 설계된...","1. 데이터통신 개요를 설명하며, 강좌 개요와 데이터 통신의 개요에 대하여 배운다....",- 파워포인트를 이용한 이론 강의\r\n- 강의 80% 질의응답 20%,없음,x
31,소프트웨어융합학부,소프트웨어융합전공,논리회로설계,정인철,전공선택,없음,"1. 수의 체계와 정보의 부호화, 부울대수의 개념을 이해한다.\r\n2. 인코더/디...",주로 강의를 통해 디지털 논리회로의 개념을 이해시킨다.\r\n매 단원이 끝날 때 연...,4.67,시험 망했는데 B+ 받음 수업은 어렵지만 자기가 그래도 자진해서 독학하면 잘 볼 수...
32,소프트웨어융합학부,소프트웨어융합전공,전공지도,이하규,전공필수,없음,- 현재 학기의 수강신청 상황을 점검하고 다음 학기 수강신청에 대해 지도한다.\r\...,"개인 발표/토론과 조별 발표/토론을 중심으로 수업이 이루어지며,\r\n개인별 심층 ...",없음,x
33,소프트웨어융합학부,소프트웨어융합전공,C++프로그래밍,이하규,전공선택,C프로그래밍,1. C++ 언어의 문법을 익힌다.\r\n2. 객체지향 프로그래밍의 개념을 숙지한다...,"매주 학습한 내용을 활용하는 과제가 주어지며, 이를 해결하여 제출해야 합니다.\r\...",4.8,항상 높은 퀄리티로 강의해주시는 교수님 C++ 듣고 싶은 학우분은 이하규 교수님 꼭...
34,소프트웨어융합학부,소프트웨어융합전공,자료구조,김명철,전공필수,- 자바 프로그래밍,1. 컴퓨터 프로그래밍에 사용되는 기본 자료구조를 소개한다. \r\n2. 알고리즘의...,- 강의 50%\r\n- 실습 50% \r\n- 매주 학습한 내용을 활용하는 과제...,3.33,매주 과제있고 매 수업마다 조별로 실습 ? 통과해야함 그래서 그 실습 통과하려고 공...
35,소프트웨어융합학부,소프트웨어융합전공,자료구조,노은하,전공필수,선수필수 과목 : Java프로그래밍,1. 컴퓨터 프로그래밍에 사용되는 기본 자료구조를 소개한다. \r\n2. 알고리즘의...,- 강의 50%\r\n- 실습 50% \r\n- 학습한 내용을 활용하는 프로그래밍...,5.0,"교수님이 상당히 잘 알려주시고, 궁금한것도 잘 받아주심. -( 5/5)\n\n소프..."
36,소프트웨어융합학부,소프트웨어융합전공,컴퓨터구조,김학수,전공선택,논리회로설계,"컴퓨터 시스템 개요, CPU의 구조와 기능, 산술과 논리 연산, 제어 장치, 기억 ...",1. 강의를 통해 컴퓨터 시스템의 구조와 원리를 설명한다. \r\n2. 단원마다 간...,4.25,연습문제 다 이해하고 푸시면 A+입니다 교수님 부드러우시고 좋아요 - (5/5)\n...
37,소프트웨어융합학부,소프트웨어융합전공,컴퓨터구조,정인철,전공선택,논리회로설계를 이수한 경우에는 도움이 됨,"컴퓨터 시스템 개요, CPU의 구조와 기능, 산술과 논리 연산, 제어 장치, 기억 ...",강의는 대부분 교수가 직접 강의를 하며 수시로 퀴즈와 토론을 포함하는 강의를 진행한...,4.0,시험 연습문제 난이도로 내시고 학점도 잘 주심 정인철 교수님 폼 미쳤다! - (5...
38,소프트웨어융합학부,소프트웨어융합전공,JSP프로그래밍,박정식,전공선택,본 과목을 이수해야 백엔드프레임워크 과목을 수강 신청할 수 있습니다.,웹프로그래밍 구조에 대하여 배우고 이클립스 통합개발환경을 통하여 직접 JSP프로그램...,파워포인트를 활용한 이론강의와 컴퓨터를 활용한 실습을 병행한다.,없음,x
39,소프트웨어융합학부,소프트웨어융합전공,백엔드프로그래밍,김선형,전공선택,"* 백엔드프로그래밍을 수강신청하기 위한 선수필수 과목: 웹개발입문, Java프로그래...","웹 개발 기초: HTML, CSS, JS\n데이터베이스 기초: SQL, MySQL\...",강의를 통해 웹 프로그래밍의 동작 원리를 설명한다.\r\n실습을 통해 웹 서버 애플...,없음,x
40,소프트웨어융합학부,소프트웨어융합전공,컴퓨터네트워크,박정식,전공선택,이 과목은 2학년 2학기에 개설한 데이터통신과목을 연장하여 강의를 진행하므로 데이터...,- 컴퓨터 네트워크 프로토콜 모델에 대해 이해한다.\n- TCP/IP 프로토콜 스택...,교수강의 80%\r\n연습문제풀이 10%\r\n점검 및 조언 10%\r\n강의는 대...,5.0,영어 원서+영어 PPT라서 시험 기간에 벼락치기할 때 조금 힘들었음.. 근데 수업은...
41,소프트웨어융합학부,소프트웨어융합전공,디지털회로실험,정인철,전공선택,논리회로설계를 이수한 경우 도움이 됨,1. 각종 계측장비의 사용법에 대해 익히고 다룰수 있도록 한다.\r\n2. 기초 전...,본 강과는 주로 실험 실습을 통해 이루어진다.\r\n학생들의 이해를 향상시키기 위해...,5.0,정통에서 믿고 듣는 정인철 교수님 시험은 역시 어려운 편임. 문제 수가 많지는 않았...
42,소프트웨어융합학부,소프트웨어융합전공,서버구축및형상관리,이승진,전공선택,"꼭 필요한 선수 과목은 없지만, 웹프로그래밍 과목을 먼저 수강해야 서버 구축 실습 ...",git을 활용한 형상 관리 기법을 학습한다.\r\n정보시스템 서버를 구축하기 위해 ...,강의 50%\r\n실습 50% \r\n\r\n매주 학습한 내용을 실습해 볼 수 있...,4.6,"깃과 깃허브, 리눅스 명령어랑 AWS 간단하게 배움 깃과 깃허브 아예 처음이라면 이..."
43,소프트웨어융합학부,소프트웨어융합전공,신호및시스템,김학수,전공선택,"공업수학, 파이썬프로그래밍",1. 신호 및 시스템의 개념 및 응용 사례\r\n2. 연속시간 주기 신호와 비주기 ...,1. 신호 및 시스템의 개념과 이론을 설명한다. \r\n2. 파이썬 프로그래밍을 통...,없음,x
44,소프트웨어융합학부,소프트웨어융합전공,웹디자인,이해신,전공선택,소프트웨어융합전공에서 웹개발입문 교과목을 이수해야 수강 신청 가능한 과목은 Java...,"- HTML, CSS 등 웹 디자인 기술을 활용한 웹 페이지 제작 기술\n- CSS...","이론 설명 후 컴퓨터를 활용한 실습 위주의 수업\r\n이론 강의 30%, 실습 70%",없음,x
45,미래융합학부,빅데이터응용전공,경영정보시스템의이해,김수림,전공필수,없음,"경영정보시스템의 개념과 구조에 대한 이해를 바탕으로, 기업 내 다양한 시스템이 어떤...",1. 이론 설명\n2. 강의시간 내 그룹활동\n3. 개인발표\n4. 중간/기말고사,없음,x
46,미래융합학부,빅데이터응용전공,빅데이터처리와시각화,김양희,전공선택,없음,"데이터 문해력의 개념과 중요성에 대한 이론적 탐구를 바탕으로, 다양한 실제 사례 분...",1. 개인 레포트\n2. 중간/기말고사\n,없음,x
47,미래융합학부,인공지능전공,빅데이터프로그래밍(Python),김수림,전공필수,없음,데이터 기반 의사결정을 위한 빅데이터 프로그래밍의 개념과 필요성에 대한 이해를 시작...,1. 이론 소개 및 실습 진행\n2. 강의 내용을 바탕으로 기말고사 전 개인 과제에...,없음,x
48,미래융합학부,인공지능전공,머신러닝입문,홍성준,전공필수,Python프로그래밍,머신 러닝의 주요 개념과 모델을 학습하고 머신 러닝 라이브러리인 사이킷런과 텐서플로...,"1) 이론 강의, 예제 코드 리뷰, 프로그래밍 실습을 병행한다.\r\n2) 매 주 ...",5.0,"강의가 깔끔해서? 좋았음 시험은 실습보다 개념, 이론 위주로 나옴 과제는 진도 나갈..."
49,미래융합학부,인공지능전공,데이터사이언스입문,이상윤,전공필수,Python프로그래밍을 수강했거나 Python 기초 역량이 있는 학생을 대상으로 합...,"1) 데이터 전처리, 시각화, 결과 분석 등 일련의 데이터 분석 과정을 학습한다.\...",본 교과목은 플립러닝(Flipped Learning) 방식으로 진행됩니다.\r\n-...,5.0,python에서 사용할 수 있는 데이터 처리 라이브러리인 pandas를 기반으로 데...
50,미래융합학부,인공지능전공,고급Python프로그래밍,홍성준,전공선택,Python프로그래밍,다양한 파이썬 라이브러리를 이해하고 이를 활용한 파이썬 프로그램 구현을 실 습한다.,"1) 이론 강의, 예제 코드 리뷰, 프로그래밍 실습을 병행한다.\r\n2) 매 주 ...",없음,x
51,미래융합학부,인공지능전공,오픈소스SW개발,이상윤,전공선택,없음,- 오픈소스 소프트웨어 이해\r\n- 개발 환경 구축 및 관리\r\n- 분산 버전관...,"실습 위주의 수업으로 진행되며, 중간고사와 기말고사는 각각 개인프로젝트와 팀프로젝트...",없음,x

In [75]:
#강의평가 데이터를\\n기준으로 나누고 (1)(2)(3)이 포함되면 나눠진 문장 단위로강의평가_낮음 컬럼에 추가
df['강의평가_낮음'] = df['강의평가'].apply(lambda x: '\n'.join([line for line in x.split('\n') if '(1)' in line or '(2)' in line or '(3)' in line]))
df['강의평가_높음'] = df['강의평가'].apply(lambda x: '\n'.join([line for line in x.split('\n') if '(4)' in line or '(5)' in line]))

print("강의평가: \n", df['강의평가'][4])
print("---------------------------------------------------------------------")
print("강의평가 낮음: \n", df['강의평가_낮음'][4])
print("---------------------------------------------------------------------")
print("강의평가 높음: \n", df['강의평가_높음'][4])

강의평가:
 과제는 ppt로 발표자료 만드는거랑 (발표는 희망자만) 다른 분반 퀴즈 풀기고 한 단원 끝날 때마다 퀴즈 봄. 그리고 수업참여 점수도 있지만 사실상 중간 기말이 40%씩이라 시험 잘 보는 것이 매우 중요함. 교수님 강의력 진짜 좋고 수업을 들어야만 성적 잘 나오는 것 같음 많이 빡세지만 그만큼 얻어가기 좋은 듯 - 23년 2학기 수강자 (5)

과제는 운영체제와 관련하여 주제 하나 선택해서 ppt 만드는 과제 하나 있었다. 퀴즈를 매 단원 끝날 때마다 봤고 퀴즈는 5문제 정도, 수업 시간에 교수님께서 간단한 문제 주면 답하는 활동 같은 거 있는데 그것도 매 수업마다 해야 함. 하지만 컴퓨터로 하는 거고, 한, 두 문제 정말 간단한 거라 부담 안 가져도 괜찮음. 처음 이 교수님 수업 들어보았는데 꽤 괜찮았음. 최대한 쉽게 설명하려 하시고 반복도 열심히 해주시고 it 과목 중 가장 열심히, 또 재밌게 들었던 것 같다. 시험이 엄청 어렵진 않아서 열심히 해서 높은 성적 받아야지 a 받을 수 있을 듯. - 23년 2학기 수강자 (5)

강의력이 엄청 좋다. 굉장히 상세하게 알려주시고, 딱봐도 잘 알고 계신게 느껴진다. 필요없는데 장 끝마다 보는 퀴즈들이 생각보다 귀찮다. 다른 사람들이 너무 열심히하는지 AO 이상 받기가 생각보다 어려울 수 있다. - 23년 2학기 수강자 (4)

중간 기말 보고 거의 매주 쪽지시험이 있었음. 과제도 쪽지시험 형식으로 진행됐는데 기한 내에만 하면 점수 다 주셔서 과제에 대한 부담은 없음. 대신 운영체제 과목이 과목이다보니 공부할 내용이 많음 오픈북이라 해도 공부할 내용이 많다. 중간 기말 평균보다 높게 나와서 a 생각했는데 b+ 나온거 보니 생각보다 잘 본 사람이 많은듯 - 21년 2학기 수강자 (5)

아 운체 ..... 진짜 운체는 점 ..... 눈물이 앞을 가린다 .... 매주 퀴즈를 보는 거라 강의는 밀릴 수 없다는 거 이거슨 확실하고 교수님도 강의 열심히 하셔서 강의 컬 낮다는 것은 아닙니다! 하지만 손으로 쓴다, 난 다 정리 하나하나 하는 편이다! 하시는 분들은 후 ... 만만치 않아여 ... 거진 운체 강의 들음서 위에 같은 성격을 가진 저는 정말 시감 많이 들였습니다. 그리고 시험 ... 진짜 극악 .... 정신없이 몰아치는 시험 ... 오픈북이어도 제대로 정리 안하면 망해요 ... 문제 수 많은데 시간은 부족 ... 그래도 나름 열심히 한 것 같지만 그만큼 학점이 안 나와서 조금 속상했어요. 물론 기말 시험 좀 망해서 그런 것 같긴 한데 TTTTT 흑흑 TTTTTT 하지만 TTTT 시험 객관식 고르는 것도 다 복수로 고르는 거라 ... 정말 열심히 하셔야 합니다 - 20년 2학기 수강자 (5)

거의 매주 쪽지시험보는데 오픈북이라고 방심하지 말길 오픈북이지만 책 볼 시간이 없기때문에 그냥 외워야함 실강이면 좋았을거같은데 녹강이라 교수님 목소리가 너무 단조로워서 지루함 ... - 20년 2학기 수강자 (4)

쪽지시험 자주 봐서 강의 안밀릴 수 있어요. 근데 진짜 중간, 기말은 쪽지 시험이랑 다르게 공부 제대로 하시길! 저는 대강 했다가 피봤네요. 제 학점은 망했지만 비대면인데 수업 컬리티 좋다고 생각한 과목 중 하나입니다! - 20년 2학기 수강자 (5)

쪽지시험이 상당히 많다는 부분과 공부를 열심히해야 좋은 점수를 받을 수 있음. 인강으로 들어서 그런지 이해가 안되는 부분이 많았고, 따로 시간을 많이 들여서 공부해야 이해가 되는 과목임. - 20년 2학기 수강자 (3)

대충 공부하면 시험망함, 시험보고나서 망했다 라는 생각이 들지만 막상 채점보면 점수가 잘 나온 과목 중 하나. 들어본 사람들은 공감할 듯 - 20년 2학기 수강자 (5)

싸강 기준 개인적으로 그냥 교수님이 좋았음. 과제는 싸강이라 없었는데 거의 매주 퀴즈가 있음, 크게 부담 되는건 아니고 어느 정도 공부 하고 오픈북이니까 강의자료 보고 풀면 됨, 문제는 시험이었는데 난이도가 좀 ... 있는 편이라 오픈북인데도 힘들었음. 학점도 그냥 공부 한만큼 나오는듯. - 20년 2학기 수강자 (4)
---------------------------------------------------------------------
강의평가 낮음:
 쪽지시험이 상당히 많다는 부분과 공부를 열심히해야 좋은 점수를 받을 수 있음. 인강으로 들어서 그런지 이해가 안되는 부분이 많았고, 따로 시간을 많이 들여서 공부해야 이해가 되는 과목임. - 20년 2학기 수강자 (3)
---------------------------------------------------------------------
강의평가 높음:
 과제는 ppt로 발표자료 만드는거랑 (발표는 희망자만) 다른 분반 퀴즈 풀기고 한 단원 끝날 때마다 퀴즈 봄. 그리고 수업참여 점수도 있지만 사실상 중간 기말이 40%씩이라 시험 잘 보는 것이 매우 중요함. 교수님 강의력 진짜 좋고 수업을 들어야만 성적 잘 나오는 것 같음 많이 빡세지만 그만큼 얻어가기 좋은 듯 - 23년 2학기 수강자 (5)
과제는 운영체제와 관련하여 주제 하나 선택해서 ppt 만드는 과제 하나 있었다. 퀴즈를 매 단원 끝날 때마다 봤고 퀴즈는 5문제 정도, 수업 시간에 교수님께서 간단한 문제 주면 답하는 활동 같은 거 있는데 그것도 매 수업마다 해야 함. 하지만 컴퓨터로 하는 거고, 한, 두 문제 정말 간단한 거라 부담 안 가져도 괜찮음. 처음 이 교수님 수업 들어보았는데 꽤 괜찮았음. 최대한 쉽게 설명하려 하시고 반복도 열심히 해주시고 it 과목 중 가장 열심히, 또 재밌게 들었던 것 같다. 시험이 엄청 어렵진 않아서 열심히 해서 높은 성적 받아야지 a 받을 수 있을 듯. - 23년 2학기 수강자 (5)
강의력이 엄청 좋다. 굉장히 상세하게 알려주시고, 딱봐도 잘 알고 계신게 느껴진다. 필요없는데 장 끝마다 보는 퀴즈들이 생각보다 귀찮다. 다른 사람들이 너무 열심히하는지 AO 이상 받기가 생각보다 어려울 수 있다. - 23년 2학기 수강자 (4)
중간 기말 보고 거의 매주 쪽지시험이 있었음. 과제도 쪽지시험 형식으로 진행됐는데 기한 내에만 하면 점수 다 주셔서 과제에 대한 부담은 없음. 대신 운영체제 과목이 과목이다보니 공부할 내용이 많음 오픈북이라 해도 공부할 내용이 많다. 중간 기말 평균보다 높게 나와서 a 생각했는데 b+ 나온거 보니 생각보다 잘 본 사람이 많은듯 - 21년 2학기 수강자 (5)
아 운체 ..... 진짜 운체는 점 ..... 눈물이 앞을 가린다 .... 매주 퀴즈를 보는 거라 강의는 밀릴 수 없다는 거 이거슨 확실하고 교수님도 강의 열심히 하셔서 강의 컬 낮다는 것은 아닙니다! 하지만 손으로 쓴다, 난 다 정리 하나하나 하는 편이다! 하시는 분들은 후 ... 만만치 않아여 ... 거진 운체 강의 들음서 위에 같은 성격을 가진 저는 정말 시감 많이 들였습니다. 그리고 시험 ... 진짜 극악 .... 정신없이 몰아치는 시험 ... 오픈북이어도 제대로 정리 안하면 망해요 ... 문제 수 많은데 시간은 부족 ... 그래도 나름 열심히 한 것 같지만 그만큼 학점이 안 나와서 조금 속상했어요. 물론 기말 시험 좀 망해서 그런 것 같긴 한데 TTTTT 흑흑 TTTTTT 하지만 TTTT 시험 객관식 고르는 것도 다 복수로 고르는 거라 ... 정말 열심히 하셔야 합니다 - 20년 2학기 수강자 (5)
거의 매주 쪽지시험보는데 오픈북이라고 방심하지 말길 오픈북이지만 책 볼 시간이 없기때문에 그냥 외워야함 실강이면 좋았을거같은데 녹강이라 교수님 목소리가 너무 단조로워서 지루함 ... - 20년 2학기 수강자 (4)
쪽지시험 자주 봐서 강의 안밀릴 수 있어요. 근데 진짜 중간, 기말은 쪽지 시험이랑 다르게 공부 제대로 하시길! 저는 대강 했다가 피봤네요. 제 학점은 망했지만 비대면인데 수업 컬리티 좋다고 생각한 과목 중 하나입니다! - 20년 2학기 수강자 (5)
대충 공부하면 시험망함, 시험보고나서 망했다 라는 생각이 들지만 막상 채점보면 점수가 잘 나온 과목 중 하나. 들어본 사람들은 공감할 듯 - 20년 2학기 수강자 (5)
싸강 기준 개인적으로 그냥 교수님이 좋았음. 과제는 싸강이라 없었는데 거의 매주 퀴즈가 있음, 크게 부담 되는건 아니고 어느 정도 공부 하고 오픈북이니까 강의자료 보고 풀면 됨, 문제는 시험이었는데 난이도가 좀 ... 있는 편이라 오픈북인데도 힘들었음. 학점도 그냥 공부 한만큼 나오는듯. - 20년 2학기 수강자 (4)

In [79]:
df['강의평가'].value_counts()

강의평가
x                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       19
없음                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       6
시험도 그렇게 안어렵고 무난해요. 수학 잘하면 학점 채우기로 들으시고 못하면 배우려고 들으시면 좋아요  - (4)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
강의가 깔끔해서? 좋았음 시험은 실습보다 개념, 이론 위주로 나옴 과제는 진도 나갈 때마다 있는데 그냥 코드 복붙하면 되는거라 괜찮았음 교수님이 은근 개그 욕심 있으심 그리고 가끔 일찍 끝내주셔유 -(5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
깃과 깃허브, 리눅스 명령어랑 AWS 간단하게 배움 깃과 깃허브 아예 처음이라면 이번에 배우면 좋다. 소신발언하자면 깃, 깃허브 이미 잘 다룬다면 다른 거 먼저 들어도 될 것 같다 -(5)\n\n킹 갓 승 진 왠만한 시험은 강의자료만으로 볼 수 있지만 제대로 배우고 뭐라도 남길 수 있을지는 개인역량 - (5)\n\n이승진 교수님이니까 시험은 4번^^…  문제 생기면 바로 해주는 교수님👍👍 시험 문제도 실제로 자주 사용하는 문제만 내십니다.  아래 후기보니까 왜 같은 문제 또 내냐는 말이 있는데 교수님이 수업시간에 말씀하셨는데 그 만큼 자주 사용하는 명령어이기 때문에 그러는 거라고 하셨습니다. -(5)\n\n믿고 듣는 이승진 교수님. 주로 git 내용과 aws로 서버 만드는 강의. 재밌어요. 시험은 필기 시험이었고 총 3번 봤고 과제는 출제하시는데 제출은 안해도 됨. 그래도 해보는 게 시험 보는 데 많은 도움이 됨. 수업 중간에 틈틈이 다른 이야기도 해주시면서 수업해서 좋아요. -(5)\n\n음... 과목자체는 어렵진 않은데 시험본 범위를 또보고 또보는건 왜 그런지 잘 모르겠음 -(3)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
정통에서 믿고 듣는 정인철 교수님 시험은 역시 어려운 편임. 문제 수가 많지는 않았음 과제는 진행한 실험에 대해 보고서 작성 + 다음주에 진행할 실험에 대한 예비보고서임 일주일에 두가지 보고서 제출하면 됨. 참고로 실험은 조별로 진행함(친구랑 같이 해도 되고 친구 없으면 교수님이 조 편성해주심) 중간고사는 없었고 기말고사만 봤음  - (5)\n\n매주 예비보고서 결과보고서 작성해야 되지만 중간고사는 없고 기말고사만 봄 - (5)\n\n수업 좋아요. 논리회로설계에서 배운 회로를 직접 만들어보는 수업. 이론 복습 간단하게 해주시고 실습 들어가요. - (5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1

In [82]:
#강의평가 x 컬럼 없음으로 교체
df['강의평가'] = df['강의평가'].replace('x', '없음')
df['강의평가'].value_counts()

강의평가
없음                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      25
과제는 ppt로 발표자료 만드는거랑 (발표는 희망자만) 다른 분반 퀴즈 풀기고 한 단원 끝날 때마다 퀴즈 봄. 그리고 수업참여 점수도 있지만 사실상 중간 기말이 40%씩이라 시험 잘 보는 것이 매우 중요함. 교수님 강의력 진짜 좋고 수업을 들어야만 성적 잘 나오는 것 같음 많이 빡세지만 그만큼 얻어가기 좋은 듯 - 23년 2학기 수강자 (5)\n\n과제는 운영체제와 관련하여 주제 하나 선택해서 ppt 만드는 과제 하나 있었다. 퀴즈를 매 단원 끝날 때마다 봤고 퀴즈는 5문제 정도, 수업 시간에 교수님께서 간단한 문제 주면 답하는 활동 같은 거 있는데 그것도 매 수업마다 해야 함. 하지만 컴퓨터로 하는 거고, 한, 두 문제 정말 간단한 거라 부담 안 가져도 괜찮음. 처음 이 교수님 수업 들어보았는데 꽤 괜찮았음. 최대한 쉽게 설명하려 하시고 반복도 열심히 해주시고 it 과목 중 가장 열심히, 또 재밌게 들었던 것 같다. 시험이 엄청 어렵진 않아서 열심히 해서 높은 성적 받아야지 a 받을 수 있을 듯. - 23년 2학기 수강자 (5)\n\n강의력이 엄청 좋다. 굉장히 상세하게 알려주시고, 딱봐도 잘 알고 계신게 느껴진다. 필요없는데 장 끝마다 보는 퀴즈들이 생각보다 귀찮다. 다른 사람들이 너무 열심히하는지 AO 이상 받기가 생각보다 어려울 수 있다. - 23년 2학기 수강자 (4)\n\n중간 기말 보고 거의 매주 쪽지시험이 있었음. 과제도 쪽지시험 형식으로 진행됐는데 기한 내에만 하면 점수 다 주셔서 과제에 대한 부담은 없음. 대신 운영체제 과목이 과목이다보니 공부할 내용이 많음 오픈북이라 해도 공부할 내용이 많다. 중간 기말 평균보다 높게 나와서 a 생각했는데 b+ 나온거 보니 생각보다 잘 본 사람이 많은듯 - 21년 2학기 수강자 (5)\n\n아 운체 ..... 진짜 운체는 점 ..... 눈물이 앞을 가린다 .... 매주 퀴즈를 보는 거라 강의는 밀릴 수 없다는 거 이거슨 확실하고 교수님도 강의 열심히 하셔서 강의 컬 낮다는 것은 아닙니다! 하지만 손으로 쓴다, 난 다 정리 하나하나 하는 편이다! 하시는 분들은 후 ... 만만치 않아여 ... 거진 운체 강의 들음서 위에 같은 성격을 가진 저는 정말 시감 많이 들였습니다. 그리고 시험 ... 진짜 극악 .... 정신없이 몰아치는 시험 ... 오픈북이어도 제대로 정리 안하면 망해요 ... 문제 수 많은데 시간은 부족 ... 그래도 나름 열심히 한 것 같지만 그만큼 학점이 안 나와서 조금 속상했어요. 물론 기말 시험 좀 망해서 그런 것 같긴 한데 TTTTT 흑흑 TTTTTT 하지만 TTTT 시험 객관식 고르는 것도 다 복수로 고르는 거라 ... 정말 열심히 하셔야 합니다 - 20년 2학기 수강자 (5)\n\n거의 매주 쪽지시험보는데 오픈북이라고 방심하지 말길 오픈북이지만 책 볼 시간이 없기때문에 그냥 외워야함 실강이면 좋았을거같은데 녹강이라 교수님 목소리가 너무 단조로워서 지루함 ... - 20년 2학기 수강자 (4)\n\n쪽지시험 자주 봐서 강의 안밀릴 수 있어요. 근데 진짜 중간, 기말은 쪽지 시험이랑 다르게 공부 제대로 하시길! 저는 대강 했다가 피봤네요. 제 학점은 망했지만 비대면인데 수업 컬리티 좋다고 생각한 과목 중 하나입니다! - 20년 2학기 수강자 (5)\n\n쪽지시험이 상당히 많다는 부분과 공부를 열심히해야 좋은 점수를 받을 수 있음. 인강으로 들어서 그런지 이해가 안되는 부분이 많았고, 따로 시간을 많이 들여서 공부해야 이해가 되는 과목임. - 20년 2학기 수강자 (3)\n\n대충 공부하면 시험망함, 시험보고나서 망했다 라는 생각이 들지만 막상 채점보면 점수가 잘 나온 과목 중 하나. 들어본 사람들은 공감할 듯 - 20년 2학기 수강자 (5)\n\n싸강 기준 개인적으로 그냥 교수님이 좋았음. 과제는 싸강이라 없었는데 거의 매주 퀴즈가 있음, 크게 부담 되는건 아니고 어느 정도 공부 하고 오픈북이니까 강의자료 보고 풀면 됨, 문제는 시험이었는데 난이도가 좀 ... 있는 편이라 오픈북인데도 힘들었음. 학점도 그냥 공부 한만큼 나오는듯. - 20년 2학기 수강자 (4)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
강의가 깔끔해서? 좋았음 시험은 실습보다 개념, 이론 위주로 나옴 과제는 진도 나갈 때마다 있는데 그냥 코드 복붙하면 되는거라 괜찮았음 교수님이 은근 개그 욕심 있으심 그리고 가끔 일찍 끝내주셔유 -(5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
깃과 깃허브, 리눅스 명령어랑 AWS 간단하게 배움 깃과 깃허브 아예 처음이라면 이번에 배우면 좋다. 소신발언하자면 깃, 깃허브 이미 잘 다룬다면 다른 거 먼저 들어도 될 것 같다 -(5)\n\n킹 갓 승 진 왠만한 시험은 강의자료만으로 볼 수 있지만 제대로 배우고 뭐라도 남길 수 있을지는 개인역량 - (5)\n\n이승진 교수님이니까 시험은 4번^^…  문제 생기면 바로 해주는 교수님👍👍 시험 문제도 실제로 자주 사용하는 문제만 내십니다.  아래 후기보니까 왜 같은 문제 또 내냐는 말이 있는데 교수님이 수업시간에 말씀하셨는데 그 만큼 자주 사용하는 명령어이기 때문에 그러는 거라고 하셨습니다. -(5)\n\n믿고 듣는 이승진 교수님. 주로 git 내용과 aws로 서버 만드는 강의. 재밌어요. 시험은 필기 시험이었고 총 3번 봤고 과제는 출제하시는데 제출은 안해도 됨. 그래도 해보는 게 시험 보는 데 많은 도움이 됨. 수업 중간에 틈틈이 다른 이야기도 해주시면서 수업해서 좋아요. -(5)\n\n음... 과목자체는 어렵진 않은데 시험본 범위를 또보고 또보는건 왜 그런지 잘 모르겠음 -(3)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
정통에서 믿고 듣는 정인철 교수님 시험은 역시 어려운 편임. 문제 수가 많지는 않았음 과제는 진행한 실험에 대해 보고서 작성 + 다음주에 진행할 실험에 대한 예비보고서임 일주일에 두가지 보고서 제출하면 됨. 참고로 실험은 조별로 진행함(친구랑 같이 해도 되고 친구 없으면 교수님이 조 편성해주심) 중간고사는 없었고 기말고사만 봤음  - (5)\n\n매주 예비보고서 결과보고서 작성해야 되지만 중간고사는 없고 기말고사만 봄 - (5)\n\n수업 좋아요. 논리회로설계에서 배운 회로를 직접 만들어보는 수업. 이론 복습 간단하게 해주시고 실습 들어가요. - (5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
영어 원서+영어 PPT라서 시험 기간에 벼락치기할 때 조금 힘들었음.. 근데 수업은 한국어로 완전 이해하기 쉽게 설명해주셔서, 수업만 열심히 들으면 어려울게 없는듯 제일 좋은 점은 화요일에 한 단원 수업 끝나면 목요일에는 수업 없음~~ 덕분에 공강 생겨서 좋았던 수업임  -(5)\n\n이론수업답게 전부 암기하면 된다. 참고로 수업 교재는 영어 원서고 무지무지 두껍고 무겁다.  참고로 수업 ppt도 영어임.  하지만 교수님이 천천히 설명해주셔서 이해하기 쉬웠다. 과제는 많지 않음 -(5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1

In [83]:
#df 저장
df.to_csv('data/cleaned_data.csv', index=False)

In [45]:
from langchain_community.document_loaders.csv_loader import CSVLoader

loader = CSVLoader(file_path='data/cleaned_data.csv', encoding='utf-8')
data = loader.load()

data[4]

Document(metadata={'source': 'data/cleaned_data.csv', 'row': 4}, page_content='학부명: IT융합자율학부\n학과명: 소프트웨어전공\n강의명: 운영체제\n교수명: 노은하\n이수구분: 전공필수\n선수과목과수강요건: Java프로그래밍, 자료구조, 컴퓨터구조의 기본 개념을 갖추고 있으면 수강에 도움이 되지만, 필수적이지는 않음\n학습내용: 컴퓨터 시스템의 개요, 운영체제 개념, 발전과정, 운영체제 구조, 프로세스와 스레드 작동방법, 병행프로세스, 상호배제, 교착상태, 기아 상태, 프로세스 스케쥴링, 메모리관리 등  컴퓨터의 역사, 작동원리와 자원관리를 이해함으로써 컴퓨터 효율성 및 편리성을 극대화 하는 방법을 습득한다..\n수업진행방식: - 강의 70%\r\n- 퀴즈와 과제 수행 30%\r\n- 강의를 주로 하되, 각 장의 주요 내용을 퀴즈를 통해 확인하고, 과제를 수행한다.\r\n- 수강생들이 선수 요건을 갖춘 경우, 일부 주제에 대해 프로그래밍 과제를 수행할 수 있다.\n별점: 4.4\n강의평가: 과제는 ppt로 발표자료 만드는거랑 (발표는 희망자만) 다른 분반 퀴즈 풀기고 한 단원 끝날 때마다 퀴즈 봄. 그리고 수업참여 점수도 있지만 사실상 중간 기말이 40%씩이라 시험 잘 보는 것이 매우 중요함. 교수님 강의력 진짜 좋고 수업을 들어야만 성적 잘 나오는 것 같음 많이 빡세지만 그만큼 얻어가기 좋은 듯 - 23년 2학기 수강자 (5/5)\n\n과제는 운영체제와 관련하여 주제 하나 선택해서 ppt 만드는 과제 하나 있었다. 퀴즈를 매 단원 끝날 때마다 봤고 퀴즈는 5문제 정도, 수업 시간에 교수님께서 간단한 문제 주면 답하는 활동 같은 거 있는데 그것도 매 수업마다 해야 함. 하지만 컴퓨터로 하는 거고, 한, 두 문제 정말 간단한 거라 부담 안 가져도 괜찮음. 처음 이 교수님 수업 들어보았는데 꽤 괜찮았음. 최대한 쉽게 설명하려 하시고 반복도 열심히 해주시고 it 과목 중 가장 열심히, 또 재밌게 들었던 것 같다. 시험이 엄청 어렵진 않아서 열심히 해서 높은 성적 받아야지 a 받을 수 있을 듯. - 23년 2학기 수강자 (5/5)\n\n강의력이 엄청 좋다. 굉장히 상세하게 알려주시고, 딱봐도 잘 알고 계신게 느껴진다. 필요없는데 장 끝마다 보는 퀴즈들이 생각보다 귀찮다. 다른 사람들이 너무 열심히하는지 AO 이상 받기가 생각보다 어려울 수 있다. - 23년 2학기 수강자 (4/5)\n\n중간 기말 보고 거의 매주 쪽지시험이 있었음. 과제도 쪽지시험 형식으로 진행됐는데 기한 내에만 하면 점수 다 주셔서 과제에 대한 부담은 없음. 대신 운영체제 과목이 과목이다보니 공부할 내용이 많음 오픈북이라 해도 공부할 내용이 많다. 중간 기말 평균보다 높게 나와서 a 생각했는데 b+ 나온거 보니 생각보다 잘 본 사람이 많은듯 - 21년 2학기 수강자 (5/5)\n\n아 운체 ..... 진짜 운체는 점 ..... 눈물이 앞을 가린다 .... 매주 퀴즈를 보는 거라 강의는 밀릴 수 없다는 거 이거슨 확실하고 교수님도 강의 열심히 하셔서 강의 컬 낮다는 것은 아닙니다! 하지만 손으로 쓴다, 난 다 정리 하나하나 하는 편이다! 하시는 분들은 후 ... 만만치 않아여 ... 거진 운체 강의 들음서 위에 같은 성격을 가진 저는 정말 시감 많이 들였습니다. 그리고 시험 ... 진짜 극악 .... 정신없이 몰아치는 시험 ... 오픈북이어도 제대로 정리 안하면 망해요 ... 문제 수 많은데 시간은 부족 ... 그래도 나름 열심히 한 것 같지만 그만큼 학점이 안 나와서 조금 속상했어요. 물론 기말 시험 좀 망해서 그런 것 같긴 한데 TTTTT 흑흑 TTTTTT 하지만 TTTT 시험 객관식 고르는 것도 다 복수로 고르는 거라 ... 정말 열심히 하셔야 합니다 - 20년 2학기 수강자 (5/5)\n\n거의 매주 쪽지시험보는데 오픈북이라고 방심하지 말길 오픈북이지만 책 볼 시간이 없기때문에 그냥 외워야함 실강이면 좋았을거같은데 녹강이라 교수님 목소리가 너무 단조로워서 지루함 ... - 20년 2학기 수강자 (4/5)\n\n쪽지시험 자주 봐서 강의 안밀릴 수 있어요. 근데 진짜 중간, 기말은 쪽지 시험이랑 다르게 공부 제대로 하시길! 저는 대강 했다가 피봤네요. 제 학점은 망했지만 비대면인데 수업 컬리티 좋다고 생각한 과목 중 하나입니다! - 20년 2학기 수강자 (5/5)\n\n쪽지시험이 상당히 많다는 부분과 공부를 열심히해야 좋은 점수를 받을 수 있음. 인강으로 들어서 그런지 이해가 안되는 부분이 많았고, 따로 시간을 많이 들여서 공부해야 이해가 되는 과목임. - 20년 2학기 수강자 (3/5)\n\n대충 공부하면 시험망함, 시험보고나서 망했다 라는 생각이 들지만 막상 채점보면 점수가 잘 나온 과목 중 하나. 들어본 사람들은 공감할 듯 - 20년 2학기 수강자 (5/5)\n\n싸강 기준 개인적으로 그냥 교수님이 좋았음. 과제는 싸강이라 없었는데 거의 매주 퀴즈가 있음, 크게 부담 되는건 아니고 어느 정도 공부 하고 오픈북이니까 강의자료 보고 풀면 됨, 문제는 시험이었는데 난이도가 좀 ... 있는 편이라 오픈북인데도 힘들었음. 학점도 그냥 공부 한만큼 나오는듯. - 20년 2학기 수강자 (4/5)')